application: alsproyectolopezmarchantenoa
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

- url: /farmacias
  script: farmacias.app

- url: /anhadirFarmacias
  script: farmacias.app

- url: /editarFarmacias
  script: farmacias.app

- url: /eliminarFarmacias
  script: farmacias.app

- url: /medicamentos
  script: medicamentos.app

- url: /anhadirMedicamentos
  script: medicamentos.app

- url: /editarMedicamentos
  script: medicamentos.app

- url: /eliminarMedicamentos
  script: medicamentos.app

- url: /images
  static_dir: images
  application_readable: true

- url: /css
  static_dir: css

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
- name: PIL
  version: latest
